[versions]
agp = "8.7.0"
kotlin = "2.0.21"
coreKtx = "1.15.0"
composeBom = "2024.12.01"
androidxTv = "1.0.0"
activityCompose = "1.9.3"
kosherJava = "2.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "androidxTv" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "androidxTv" }
kosherjava-zmanim = { group = "com.kosherjava", name = "zmanim", version.ref = "kosherJava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
